fix compiler warnings
ke6jjj/ka9q-unix pull request #1
Opened 2019-09-21 03:52 UTC by erikarn

This gets us pretty close to having -Wall -Werror on by default.

2019-09-21 05:58 UTC, ke6jjj requested changes
I think all of this is perfect! ... except for the fflush changes.

For the fflush changes you're certainly in the right direction. But I think this problem is better solved by setting the buffering mode on the file when it is opened. If we set the file buffering on open here (line 257ish):

            if((ifp->trfp = kfopen(argv[3],APPEND_TEXT)) == NULL){
                    kprintf("Can't write to %s\n",argv[3]);
            }
            ksetvbuf(ifp->trfp,NULL,_kIOLBF,kBUFSIZ);

then not only is it a simpler fix, but we'll be more in line with the rest of the code base. Consider all these examples:

```
ax25cmd.c:	ksetvbuf(sp->network,NULL,_kIOLBF,kBUFSIZ);
ftpserv.c:	ksetvbuf(ftp.control,NULL,_kIOLBF,kBUFSIZ);
nrcmd.c:	ksetvbuf(sp->network,NULL,_kIOLBF,kBUFSIZ);
telnet.c:	ksetvbuf(sp->network,NULL,_kIOLBF,kBUFSIZ);
telnet.c:	ksetvbuf(sp->output,NULL,_kIOLBF,kBUFSIZ);
telnet.c:			ksetvbuf(tn->session->network,NULL,_kIOLBF,kBUFSIZ);
tnserv.c:	ksetvbuf(fp,NULL,_kIOLBF,kBUFSIZ);
ttylink.c:	ksetvbuf(sp->network,NULL,_kIOLBF,kBUFSIZ);
```

2019-09-21 15:48 UTC, erikarn commented
ok, check now. this is now squished into one commit and the changes requested were made.

2019-09-23 22:24 UTC, ke6jjj approved these changes

2019-09-23 22:24 UTC, ke6jjj commented on trace.c
> -	kfprintf(fp,"\n");
I think I forgot to mention: line buffer mode makes a flush at every newline. That means the change on this line is unnecessary, and perhaps, actually introduces a bug, since there's now no newline in the output where there used to be one before.

2019-09-23 22:24 UTC, merged